---
title: "reaction_time_simulation"
output: html_document
date: "2024-03-27"
---

### Read libraries
```{r}
library(tidyverse)
library(EZ2)
library(fdrtool)
library(ez)
library(rtdists)
library(gamlss.dist)
library(lme4)
library(lmerTest)
library(parallel)
library(papaja)
```

### Load empirical data summary
```{r}
load("flanker2020.Rda")
flanker2020_summary = flanker2020_summary %>% 
  rename(glob_rtm = mean_rt,
         glob_rtv = var_rt,
         glob_rts = sd_rt,
         glob_rtc = correct_percent) %>% 
  dplyr::select(-"N")
```

### Create participants 
```{r}
source_data = data.frame(participant_id = c(1:100),
                         rt_intercept = rnorm(100, 0, 0.1),
                         rt_random_slope = rnorm(100, 0, 0.01)) %>% 
  uncount(2) %>% 
  mutate(is_congruent = rep(0:1, each=1, length.out=n())) %>% 
  uncount(2) %>% 
  mutate(prev_congruent = rep(0:1, each=1, length.out=n())) %>% 
  left_join(flanker2020_summary, by=c("is_congruent","prev_congruent")) %>% 
  mutate(mean_rt = case_when(is_congruent == 1 ~ glob_rtm+rt_intercept-rt_random_slope,
                             is_congruent == 0 ~ glob_rtm+rt_intercept+rt_random_slope))
```


```{r}
source_data %>% ggplot()+
  aes(x=mean_rt) +
  geom_histogram()
```
```{r}
cse_data = source_data %>% 
  group_by(is_congruent,prev_congruent) %>% 
  summarize(rt_mean = mean(mean_rt)) %>% 
  ggplot()+
  aes(x=as.factor(prev_congruent), y=rt_mean, group=as.factor(is_congruent))+
  geom_point()+
  geom_path()

cse_data
```
## check congruency effect data
```{r}
ce_data = source_data %>% 
  group_by(participant_id, is_congruent) %>% 
  summarize(mean_rt = mean(mean_rt)) %>% 
  pivot_wider(values_from = mean_rt, names_from = is_congruent, names_prefix = "con_") %>% 
  mutate(ce = con_0 - con_1)

hist(ce_data$ce)
```


```{r}
source_data <- source_data %>%
  filter(glob_rtc>.5) %>% 
  mutate(Result = pmap(list(
    ifelse(glob_rtc==1, 1-1/(N*2),glob_rtc),
    glob_rtv,
    mean_rt,
    s=1),
    Data2EZ),
         v = map_dbl(Result, "v"),
         a = map_dbl(Result, "a"),
         Ter = map_dbl(Result, "Ter")) %>% 
  dplyr::select(-Result)
```

### Create data with diffusion model
```{r}
testdf = source_data %>%
  filter(Ter>.1) %>% 
  mutate(Result=pmap(
    list(80,
         a=a,
         v=v,
         t0=Ter),
    rdiffusion)) %>% 
  unnest(Result)

hist(testdf$rt)
```
### Filtering
```{r}
participant_summary = testdf %>% 
  group_by(participant_id, is_congruent, prev_congruent) %>% 
  summarize(participant_mean_rt = mean(rt),
            participant_sd_rt = sd(rt))

testdf = testdf %>% 
  left_join(participant_summary, by = c("participant_id", "is_congruent", "prev_congruent")) %>% 
  mutate(rt_zscore = ((rt-participant_mean_rt)/participant_sd_rt))
```


```{r}
testfilter = testdf %>% 
  filter(response == "upper",
         abs(rt_zscore)<2)
```


```{r}
ggplot(data=testfilter, aes(x = is_congruent, y = rt))+
  geom_bar(stat = "identity")
```

```{r}
csemodel = lmer(rt ~ is_congruent*prev_congruent + (1+is_congruent|participant_id),data=testfilter)
bigmodel = summary(csemodel)
bigmodel
```
```{r}
testfilter %>% group_by(is_congruent, prev_congruent) %>% 
  summarize(mean_rt =mean(rt, na.rm = T)) %>% 
  ggplot()+
  aes(x=as.factor(prev_congruent), y=mean_rt, color=as.factor(is_congruent), group=as.factor(is_congruent))+
  geom_point()+
  geom_path()
```

```{r}
testfilter %>%
  mutate(is_congruent = ifelse(is_congruent == 0, "Incongruent", "Congruent"),
         rt = rt * 1000) %>% 
  group_by(is_congruent) %>% 
  summarize(N = n(),
            mean_rt =mean(rt, na.rm = T),
            sd_rt =sd(rt, na.rm = T),
            se_rt = sd_rt/sqrt(N)) %>% 
  ggplot()+
  aes(x=as.factor(is_congruent), y=mean_rt)+
  geom_point()+
  theme_apa()+
  geom_errorbar(size=0.5,aes(ymin=mean_rt-se_rt,
                    ymax=mean_rt+se_rt,
                    width=.2))+
  xlab("Trial congruency")+
  ylab("Mean reaction time (ms)")
ggsave("congruency_effect.jpg", width = 7, height = 5)
```


```{r}
bigmodel$coefficients[20]
```

```{r}
anova_summary = testfilter %>% 
  group_by(participant_id, is_congruent, prev_congruent) %>% 
  summarize(mean_rt = mean(rt, na.rm=T)) %>% 
  ungroup() %>% 
  group_by(participant_id) %>% 
  filter(n_distinct(is_congruent, prev_congruent)==4) %>% 
  mutate(is_congruent = as.factor(is_congruent),
         prev_congruent = as.factor(prev_congruent))

csenova <- ezANOVA(data = anova_summary,
                         dv = mean_rt,
                         wid = as.factor(participant_id),
                         within = .(is_congruent, prev_congruent)
                   )

csenova$ANOVA$p[3]
print(csenova)
```

```{r}
sd2list = vector("list", 100)
sd3list = vector("list", 100)
nonelist = vector("list", 100)
for(j in 1:100){
  sd2list[[j]] = test_simulation(flanker2020_summary, 50,80,2, "2SD")
  print(j)
}
sd2df = as.data.frame(do.call(rbind, sd2list))

for(j in 1:100){
  sd3list[[j]] = test_simulation(flanker2020_summary, 50,80,2.5, "2.5SD")
  print(j)
}
sd3df = as.data.frame(do.call(rbind, sd3list))

for(j in 1:100){
  nonelist[[j]] = test_simulation(flanker2020_summary, 50,80,3, "3SD")
  print(j)
}
nonedf = as.data.frame(do.call(rbind, nonelist))

alldf = rbind(sd2df,sd3df,nonedf)
colnames(alldf) = c("estimate","slope_p", "intercept_p", "anova_p","filtering")

alldf %>% group_by(filtering) %>% 
  summarize(intercept_slope_melr = mean(as.integer(as.logical(slope_p)), na.rm=T),
            intercept_melr = mean(as.integer(as.logical(intercept_p)), na.rm=T),
            anova = mean(as.integer(as.logical(anova_p)), na.rm=T))
```
```{r}
cl = makeCluster(3)
clusterExport(cl, c("simulate_data","test_simulation", "test_sequences","flanker2020_summary"), 
              envir=environment())

parameters80 = list(list(10,100,80),list(10,200,80), list(10,300,80))
trial_80_results = lapply(parameters80, function(x) do.call(test_sequences, x))

parameters160 = list(list(100,100,160),list(100,200,160), list(100,300,160))
trial_160_results = lapply(parameters160, function(x) do.call(test_sequences, x))

```

## Plots
```{r}
load("large_effect.Rda")
load("small_effect.Rda")
load("no_effect.Rda")

large_plot_data = large_effect %>% 
  mutate(is_congruent = ifelse(is_congruent == 0, "incongruent", "congruent"),
         prev_congruent = ifelse(prev_congruent == 0, "incongruent", "congruent"),
         reaction_time = glob_rtm * 1000) %>% 
  mutate(prev_congruent = factor(prev_congruent, levels=c("congruent","incongruent"))) %>% 
  ggplot()+
  aes(y=reaction_time, x=prev_congruent, color=is_congruent, group = is_congruent)+
  geom_path(linewidth=1.5)+
  papaja::theme_apa()+
  geom_point(size=3)+
  theme(legend.position = "none")
```
```{r}
large_plot_data
ggsave("large_plot.png", large_plot_data, width = 5, height = 3)
```

```{r}
small_plot_data = small_effect %>%  
mutate(is_congruent = ifelse(is_congruent == 0, "incongruent", "congruent"),
         prev_congruent = ifelse(prev_congruent == 0, "incongruent", "congruent"),
         reaction_time = glob_rtm * 1000) %>% 
  mutate(prev_congruent = factor(prev_congruent, levels=c("congruent","incongruent"))) %>% 
  ggplot()+
  aes(y=reaction_time, x=prev_congruent, color=is_congruent, group = is_congruent)+
  geom_path(linewidth=1.5)+
  papaja::theme_apa()+
  geom_point(size=3)+
  theme(legend.position = "none")

small_plot_data
ggsave("small_plot.png", small_plot_data, width = 5, height = 3)
```

```{r}
no_plot_data = no_effect %>%  
mutate(is_congruent = ifelse(is_congruent == 0, "incongruent", "congruent"),
         prev_congruent = ifelse(prev_congruent == 0, "incongruent", "congruent"),
         reaction_time = glob_rtm * 1000) %>% 
  mutate(prev_congruent = factor(prev_congruent, levels=c("congruent","incongruent"))) %>% 
  ggplot()+
  aes(y=reaction_time, x=prev_congruent, color=is_congruent, group = is_congruent)+
  geom_path(linewidth=1.5)+
  papaja::theme_apa()+
  geom_point(size=3)+
  theme(legend.position = "none")

no_plot_data
ggsave("no_plot.png", no_plot_data, width = 5, height = 3)
```


