---
title: "demo"
output: html_document
date: "2024-06-21"
---

```{r}

library(tidyverse)
library(EZ2)
library(fdrtool)
library(ez)
library(rtdists)
library(gamlss.dist)
library(lme4)
library(lmerTest)
library(parallel)
library(papaja)
source("cse_simul.R")
```

```{r}
load("small_effect.Rda")
load("large_effect.Rda")
```

```{r}
sample_data = simulate_data(small_effect, 200, 160)

sample_data%>% ggplot()+
  aes(x=rt) +
  geom_histogram()
```
```{r}
participant_summary <- sample_data %>% 
    mutate(correct = ifelse(response == "upper", 1, 0)) %>% 
    group_by(participant_id, is_congruent, prev_congruent) %>% 
    summarize(N = n(),
              participant_mean_rt = mean(rt),
              participant_var_rt = var(rt),
              participant_sd_rt = sd(rt),
              participant_correct_percent = mean(correct)) %>% 
    ungroup()

testdf <- sample_data %>% 
    left_join(participant_summary, by = c("participant_id", "is_congruent", "prev_congruent")) %>% 
    mutate(rt_zscore = ((rt - participant_mean_rt) / participant_sd_rt))
  
testfilter <- testdf %>% 
    filter(response == "upper",
           abs(rt_zscore) < 100)
```

```{r}
full_csemodel <- lmer(rt ~ prev_congruent*is_congruent + (1 + prev_congruent*is_congruent | participant_id), data = testfilter, control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
full_csemodel_summary <- summary(full_csemodel)
full_csemodel_summary
  
```


```{r}
participant_summary = sample_data %>% 
    mutate(correct = ifelse(response == "upper", 1, 0)) %>% 
    group_by(participant_id, is_congruent, prev_congruent) %>% 
    summarize(N = n(),
              participant_mean_rt = mean(rt),
              participant_var_rt = var(rt),
              participant_sd_rt = sd(rt),
              participant_correct_percent = mean(correct)) %>% 
    ungroup()
  
  diffusion_parameters = participant_summary %>% 
    mutate(Result = pmap(list(
      ifelse(participant_correct_percent==1, 1-1/(N*2),participant_correct_percent),
      participant_var_rt,
      participant_mean_rt,
      s=1),
      Data2EZ),
      v = map_dbl(Result, "v"),
      a = map_dbl(Result, "a"),
      Ter = map_dbl(Result, "Ter")) %>% 
    dplyr::select(-Result) %>% 
    mutate(is_congruent = as.factor(is_congruent),
           prev_congruent = as.factor(prev_congruent),
           participant_id = as.factor(participant_id))
```

```{r}
diffusion_summary = diffusion_parameters %>% 
  group_by(prev_congruent, is_congruent) %>% 
  summarize(mean_rt = mean(participant_mean_rt, na.rm=T),
            mean_v = mean(v, na.rm = T),
            mean_a = mean(a, na.rm = T),
            mean_Ter = mean(Ter, na.rm = T))
```


```{r}
diffusion_summary %>% ggplot()+
  aes(x=prev_congruent, y = mean_v, color = is_congruent, group= is_congruent) +
  geom_point()+
  geom_path()
```

```{r}
diffusion_summary %>% ggplot()+
  aes(x=prev_congruent, y = mean_a, color = is_congruent, group= is_congruent) +
  geom_point()+
  geom_path()
```
```{r}
diffusion_summary %>% ggplot()+
  aes(x=prev_congruent, y = mean_Ter, color = is_congruent, group= is_congruent) +
  geom_point()+
  geom_path()
```

```{r}
diffusion_summary %>% ggplot()+
  aes(x=prev_congruent, y = mean_rt, color = is_congruent, group= is_congruent) +
  geom_point()+
  geom_path()

```

