# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_sequence <- function(n_trials) {
    .Call(`_congruentSeq_generate_sequence`, n_trials)
}

rcpp_hello_world <- function() {
    .Call(`_congruentSeq_rcpp_hello_world`)
}

